FROM debian:stretch
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    autotools-dev \
    debmake \
    debootstrap \
    devscripts \
    dh-autoreconf \
    dh-make \
    equivs \
    lintian
CMD [ "bash" ]
